FROM ubuntu
WORKDIR /mnt
RUN apt-get update && apt-get install openjdk-11-jdk maven wget git unzip -y
EXPOSE 8080
RUN git clone https://github.com/Shantanumajan6/project.git
RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.90/bin/apache-tomcat-9.0.90.zip
RUN unzip apache-tomcat-9.0.90.zip
RUN chmod -R 777 apache-tomcat-9.0.90
WORKDIR /mnt/project
RUN mvn clean install
RUN cp /mnt/project/LoginWebApp.war /mnt/apache-tomcat-9.0.90/webapps
WORKDIR /mnt/apache-tomcat-9.0.90/bin
RUN ./startup.sh
